 steps:

 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/webapp-run:$COMMIT_SHA', './cloud_run']

 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/webapp-run:$COMMIT_SHA']

 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - run
   - deploy
   - webapp-run
   - --image=gcr.io/$PROJECT_ID/webapp-run:$COMMIT_SHA
   - --region=europe-west1
   - --platform=managed
   - --allow-unauthenticated
   - --port=5000
 images:
 - 'gcr.io/$PROJECT_ID/webapp-run:$COMMIT_SHA'

